### ISSUE TITLE
"Value should be a JSON object" appeared on discovery rule.

### ISSUE THREAD

**Issue by HE-SCSK** [vkostr/InfiniBox-Zabbix-integration#1]
I installed the InfiniBox-Zabbix agent and set up it.
But the discovery items always return "Value should be a JSON object".
How I can fix this error?

**Comment by vkostr** [comment]
Sorry, I missed this issue. Is it still relevant?

**Comment by hari083** [comment]
Hi yes we also see this same issue. Not sure if HE-SCSK resolved it. Can anyone tell us how to resolve it?

**Comment by vkostr** [comment]
Hi hari083!
Maybe some authentication rules were changed. Could you please run any discovery script manually in OS and share output?

**Comment by HE-SCSK** [comment]
Hi All,

I have to setup Zabbix environment to do this additional test.
It takes a time. Please wait a moment.

Regards,
Hideki Endo

**Comment by hari083** [comment]
Hi Vkostr,

I ran the "infzabbix_hostlist.py" script manually and I got below as output

{"data": [{"{#HOSTNAME}": "Actual host 1"}, {"{#HOSTNAME}": "Actual Host 2"}]}

But in the Zabbix Discovery section of the host discovery still shows the same error.

**Comment by vkostr** [comment]
that's absolutely valid JSON. What Zabbix and Python version do you use? I will try to reproduce it later, probably this week.
Regards,
Vasily

**Comment by vkostr** [comment]
@hari083 could you please share versions of Zabbix and Python, so I can try to help?

**Comment by vkostr** [comment]
Closed due no answer
